### ISSUE TITLE
Document render-content

### ISSUE THREAD

**Issue by sivakumar-kailasam** [smile-io/ember-polaris#164]
`render-content` is useful in many cases where we need to support either text/component being passed in is one of the fields of the polaris components. 

This needs to be included in the docs along with any limitations it may have.

**Comment by andrewpye** [comment]
Currently the `ember-polaris` component properties that get passed to `render-content` is pretty low as we only added that quite recently. Over time we'll look at using `render-content` in those places that should support it, and we'll make sure we update the docs as we go. As such I'm not convinced there's any need to document `render-content` itself, since it's (currently) completely internal to `ember-polaris`'s components. For that reason I'm going to close this, but feel free to reopen or comment further if you disagree! 👍

**Comment by sivakumar-kailasam** [comment]
I meant it as a document for contributors of the addon. Something like, here are some useful internals that you could use to improve/match the components in this repo to polaris' spec.

**Comment by andrewpye** [comment]
Ah OK. Yes we could do that... another thought I've had is that `render-content` is pretty generic so it's a candidate for becoming its own addon (with its own documentation, of course 😉). Your suggestion is a nice idea for making this accessible to first-time contributors without having to go through a PR review to find out this stuff exists... will give it some more thought 👍
